server:
  port: 18402
spring:
  datasource:
    url: jdbc:mysql://mysql:13306/sm_oauth_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 5000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 5000 #服务请求处理超时时间（毫秒）
  #MaxAutoRetries: 1 # 对当前实例的重试次数