server:
  port: 18001
spring:
  ## GateWay配置
  cloud:
    gateway:
      routes:
        - id: pay-service  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://platform-pay-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/service1/**  # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 # 表示在将请求发送到下游之前从请求中剥离的路径个数
        - id: pay-service2
          uri: lb://platform-pay-service2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1
        - id: platform-auth
          uri: lb://platform-auth
          predicates:
            - Path=/platform-auth/**
          filters:
            - StripPrefix=1